#' Make and save plots with \code{\link{lavaanPlot::lavaanPlot}}
#'
#' Saves a Structural Equation Model (SEM) plot generated by \code{\link{lavaanPlot::lavaanPlot}}.
#' The function handles intermediate steps, including exporting the plot to SVG and converting to PNG.
#'
#' @name saveLavaanPlot
#' @title Save Lavaan Plot
#' @docType package
#' @author Jasmijn Bazen \email{j.l.bazen@students.uu.nl}
#' @export
#'
#' @importFrom DiagrammeRsvg export_svg
#' @importFrom rsvg rsvg_png
#' @importFrom lavaanPlot lavaanPlot
#'
#' @examples
#' \dontrun{
#' Save_LavaanPlot(fit = SEMModel1,
#'                 filePath = "path/to/your/SEMModel.png",
#'                 coefs = TRUE,
#'                 stand = TRUE,
#'                 sig = 0.05,
#'                 stars = "regress",
#'                 width = 1000)
#' }
#'
# Function to fit the SEM model, generate the plot, and save it
#' @param fit A fitted \code{\link{lavaan::lavaan}} SEM model object (e.g., created using \code{cfa()} or \code{sem()}).
#' @param filePath A character string with the path to save the plot, including the file name and extension (e.g., "path/to/file.png").
#' @param coefs Logical. Whether to display path coefficients. Default is \code{TRUE}.
#' @param stand Logical. Whether to use standardized coefficients. Default is \code{TRUE}.
#' @param sig Numeric. The significance level to display. Default is \code{0.05}.
#' @param stars Character. If \code{"regress"}, significant coefficients are marked with stars. Default is \code{"regress"}.
#' @param width Numeric. Width of the plot in pixels. Default is \code{1000}.
#'
#' @return A saved plot of the SEM model as a PNG file.
#'
#' @seealso \link{lavaanPlot}, \link{lavaan}
#'
#'
saveLavaanPlot <- function(fit, filePath, coefs = TRUE, stand = TRUE, sig = 0.05,
                           stars = "regress", width = 1000) {

  # Validate the input model
  if (!inherits(fit, "lavaan")) {
    stop("The 'fit' argument must be a valid lavaan model object.")
  }
  if (!grepl("\\.png$", filePath)) {
    stop("The 'filePath' must end with '.png'.")
  }

  # Ensure the target directory exists
  dir_path <- dirname(filePath)
  if (!dir.exists(dir_path)) {
    cat("The directory", dir_path, "does not exist. Creating it now.\n")
    if (!dir.create(dir_path, recursive = TRUE)) {
      stop("Failed to create directory: ", dir_path)
    }
  }

  # Generate the SEM plot
  cat("Generating SEM plot...\n")
  sem_plot <- tryCatch(
    lavaanPlot::lavaanPlot(
      model = fit,
      coefs = coefs,
      stand = stand,
      sig = sig,
      stars = stars
    ),
    error = function(e) stop("Failed to generate plot: ", e$message)
  )

  # Check if the plot is valid
  if (!inherits(sem_plot, "grViz")) {
    stop("The plot generated by `lavaanPlot` is not valid.")
  }

  # Save as .svg in the same directory as the output file and convert to .png
  svg_file <- file.path(dir_path, "temp_plot.svg")  # Temporary file in target directory
  png_file <- filePath

  tryCatch({
    svg_output <- DiagrammeRsvg::export_svg(sem_plot)
    writeLines(svg_output, svg_file)       # Write SVG to filePath directory
    rsvg::rsvg_png(svg_file, filePath)     # Convert to PNG
    cat("File saved to:", normalizePath(filePath), "\n")
  }, error = function(e) {
    stop("Error during SVG to PNG conversion: ", e$message)
  }, finally = {
    if (file.exists(svg_file)) file.remove(svg_file)  # Clean up the temp file
  })

  tryCatch({
    print(lavaanPlot::lavaanPlot(
      model = fit,
      coefs = coefs,
      stand = stand,
      sig = sig,
      stars = stars
    ))
  }, error = function(e) {
    cat("Error rendering the plot: ", e$message, "\n")
  })


}
